### ISSUE TITLE
Is it hosted anywhere online?

### ISSUE THREAD

**Issue by iamsudip** [dtchanpura/zebpay-api-ui#1]
* Is this project hosted somewhere?

* Do you plan to add analytics like last 6 months data, today's top/bottom price etc.?

**Comment by dtchanpura** [comment]
* It is just an UI so it can be accessed from https://dcpri.me/zebpay-api-ui/
* This is meant to be just an UI to show what the current price and how much your bitcoins worth, so no analytics in this project, but it is certainly a good idea.

**Comment by iamsudip** [comment]
Clean UI, it will be nice to have support for other currencies as well.
Anyways thanks, closing the ticket.
